In [1]:
import numpy as np



In [3]:
#Create an array
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [5]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array.npy',arr)

In [6]:
#Change arr
arr = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Lets see the original saved copy
arr1=np.load('my_array.npy')

In [9]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr1)

In [13]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['y']

array([0, 1, 2, 3, 4])

In [17]:
#Now lets remove them from the memory
del arr
del arr1


In [20]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')


In [21]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])