In [1]:
import numpy as np



In [2]:
5/2

2.5

In [16]:
#Takes care of floats
from __future__ import division

In [14]:
# Create array
arr1 = np.array([[1,2,3],[8,10,12]])

#Show
arr1


array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [15]:
#Multiplying Arrays
arr1/arr1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [5]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
#Arithmetic operations with scalars on array
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [9]:
#Exponential operation
arr1 / 3

array([[ 0.33333333,  0.66666667,  1.        ],
       [ 2.66666667,  3.        ,  3.33333333]])