In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [4]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [8]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [2]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([-1.21720009,  1.52468808, -0.55671877, -0.26121915, -1.34029489,
       -1.00401189,  0.88320137,  0.42068333,  1.46262607,  0.04001993])

In [3]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([-0.1369275 ,  0.16559122,  1.14571647, -0.47857307, -1.28245537,
        1.07014604,  0.09658135,  0.84768367,  0.1800281 , -0.62887642])

In [7]:
#Addition
np.add(A,B)

array([-1.35412759,  1.69027929,  0.5889977 , -0.73979223, -2.62275026,
        0.06613415,  0.97978273,  1.268367  ,  1.64265417, -0.58885649])

In [8]:
#Finding max or min between two arrays
np.maximum(A,B)

array([-0.1369275 ,  1.52468808,  1.14571647, -0.26121915, -1.28245537,
        1.07014604,  0.88320137,  0.84768367,  1.46262607,  0.04001993])

In [16]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [11]:
np.sin(4.55)

-0.98684385850323653

In [15]:
np.sin(-13.456)

-0.77683842502993372