In [1]:
# Creating Numpy arrays
import numpy as np

# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4,5,6]

my_array1 = np.array(my_list1)



In [2]:
#Print out array

my_array1

array([1, 2, 3, 4, 5, 6])

In [8]:
# Make another list
my_list2 = [11,22,33,4,4,6]

#Make a list of lists
my_lists = [my_list1,my_list2]

#show combined list
#my_lists

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2
#my_lists

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33,  4,  4,  6]])

In [9]:
#Lets get the size of the array
my_array2.shape

(2, 6)

In [10]:
#Find out the data tyoe of the array
my_array2.dtype

dtype('int64')

In [12]:
#Making special case arrays

#Zeros
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
#Ones
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
# An empty array

np.empty(5)
#np.empty((3,4))

array([  0.00000000e+000,   0.00000000e+000,   2.18532928e-314,
         1.49166824e-154,   0.00000000e+000])

In [13]:
#Identity array
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [15]:
# Using a range

np.arange(5,10,1)

array([5, 6, 7, 8, 9])